### ISSUE TITLE
Error Scan

### ISSUE THREAD

**Issue by chenoi** [phantom0301/Cynops#1]
Hi
Thanks for sharing and I'm test it on my machine.

I'm getting page error when submit the scan for example 192.168.0.0/24

**Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

May I know what I'm doing wrong or how to resolve it. Thanks

output from my console

/home/ch/Cynops/app/main/views.py:34: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = IPscannerForm()
[2018-09-19 07:55:41,701] ERROR in app: Exception on /scan [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ch/Cynops/app/main/views.py", line 38, in scan
    nm1 = NmapProcess(ip, options="-sn")
  File "/usr/local/lib/python2.7/dist-packages/libnmap/process.py", line 104, in __init__
    raise EnvironmentError(1, "nmap is not installed or could "
EnvironmentError: [Errno 1] nmap is not installed or could not be found in system path
10.44.4.44 - - [19/Sep/2018 07:55:41] "POST /scan HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/home/ch/Cynops/app/main/errors.py", line 10, in internal_server_error
    return render_template('500.html'), 500
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: 500.html

**Comment by phantom0301** [comment]
ERROR info: 'nmap is not installed or could not be found in system path'
I think this may be  because the environment is not satisfied.

**Comment by chenoi** [comment]
Hi,
I have installed nmap as per requirement as Im able to run the command over
cli.
Environment is not satisfied? Im running on ubuntu16.04
May I know how to set nmap in system path. Please advise further. Thanks.

**Comment by phantom0301** [comment]
/app/main/views.py  line 38

> nm1 = NmapProcess(ip, options="-sn")

You can set the nmap path by the parameter "fqp".

> nm1 = NmapProcess(ip, options="-sn",fgp=path)

**Comment by chenoi** [comment]
Hi,

I have added
nm1 = NmapProcess(ip, options="-sn",fgp="/usr/bin/nmap")

and enter the web
192.168.0.0/24

but when enter the subnet still got the same web error via 127.0.0.1/scan
page
Internal Server Error
